# Generated by Django 4.2.28 on 2026-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_under',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
