# Generated by Django 4.2.28 on 2026-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0004_branch_warehouse_tenant_department_branch_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='plan_type',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Standard', 'Standard')], max_length=50),
        ),
    ]
