# Generated by Django 4.2.28 on 2026-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0005_branch_country_branch_postcode_branch_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmeeting',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='call_details',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='elevencall',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hubspotconfig',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inboundcalls',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='outboundlead',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rateus',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='widgetcalls',
            name='user_data',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
