# Generated by Django 4.2.28 on 2026-02-19 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0006_bookmeeting_user_data_call_details_user_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='brn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='business_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='clinic_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='controlled_medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='dental_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='industry_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='mi2u_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='sst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
