# Generated by Django 4.2.28 on 2026-02-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0007_branch_brn_branch_business_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='owner',
        ),
    ]
