# Generated by Django 4.2.28 on 2026-02-23 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0008_remove_branch_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255)),
                ('primary_language', models.CharField(max_length=100)),
                ('secondary_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('system_prompt', models.TextField()),
                ('tenant_id', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=100)),
                ('voice_name', models.CharField(max_length=100)),
                ('agent_id', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=100)),
                ('widget_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
