# Generated by Django 4.2.28 on 2026-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0009_aiassistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='agent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='branch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='voice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='voice_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
