# Generated by Django 4.2.28 on 2026-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0010_alter_aiassistant_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistant',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='assistant_files/'),
        ),
    ]
