"""
Django settings for Dubai_Client project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APPEND_SLASH = True
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-&xr)0(ue9)w&72i8=ytwfl(b6$d_y4ea6#d3_fzr4d_!f3*+5%'
# SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Twilio Configuration
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&xr)0(ue9)w&72i8=ytwfl(b6$d_y4ea6#d3_fzr4d_!f3*+5%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'api.talentpulse.space', '143.110.251.242','www.rasul.colrecords.com', 'rasul.colrecords.com', 'https://colrecords.com']

from corsheaders.defaults import default_headers, default_methods



TWILIO_AUTH_TOKEN = '709c4037be3a52b3dc0724ea559a2497'
TWILIO_PHONE_NUMBER = '+16205248692'

ELEVENLABS_API_KEY = 'sk_1a5d0d2ce95649390c64408eb4b83bad1d890e670ea720fe'
ELEVENLABS_AGENTS = 'agent_01jxcc5cz8ff0shqshxqv1fvcn'
# ELEVENLABS_AGENT_DUBAI = 'agent_1401k275e8vbeygv8nwd9fqaq765'
ELEVENLABS_AGENT_HEALTHCARE = "agent_2701kcjs6rh8f0gsafa3pzrgw41x"
ELEVENLABS_AGENT_DUBAI = 'agent_01jxcc5cz8ff0shqshxqv1fvcn'
AGENT_PHONE_NUMBER_ID ='phnum_01jxq3cy9fe4aas18f477pp0z5'
AGENT_PHONE_NUMBER_ID_DUBAI = 'phnum_3601k5tk7w0me4ftejn8e9fmgn15'




POSTMARK_API_TOKEN = '099f17cd-428e-4eda-bace-670c7806f2f3'
POSTMARK_SENDER_EMAIL= 'recruiter@talentpulse.space' 
POSTMARK_RECIPIENT_EMAIL= 'dinahkezia@gmail.com'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'Client_app'
]

CORS_ALLOWED_ORIGINS = [
    "https://localhost", 
    "https://api.talentpulse.space",
    "http://143.110.251.242:8002", 
    "http://143.110.251.242",
    "https://colrecords.com",
    "https://www.colrecords.com",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "content-type",
    "authorization",
]
CORS_ALLOW_METHODS = list(default_methods) + [
    "OPTIONS",
]

CORS_TRUSTED_ORIGINS = [
     "https://api.talentpulse.space",
     "http://143.110.251.242:8002",
     "http://143.110.251.242",
     "https://colrecords.com",
     "https://www.colrecords.com",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'Client_app.middleware.RoleBasedAccessMiddleware',
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'Dubai_Client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dubai_Client.wsgi.application'
AUTH_USER_MODEL = 'Client_app.CustomUser'
LOGIN_URL = '/login'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
